import 'package:flutter/material.dart';

class Task {
  final String title;
  final String category;
  final String priority;
  final IconData mainIcon;
  final Color mainIconColor;
  final IconData priorityIcon;
  final String progress;
  final String dueDate;
  final String assignedTo;
  final String status;
  final Color progressColor;
  final Color priorityIconColor;
  final int page;

  Task({
    required this.title,
    required this.category,
    required this.priority,
    required this.mainIcon,
    required this.mainIconColor,
    required this.priorityIcon,
    required this.progress,
    required this.dueDate,
    required this.page,
    required this.assignedTo,
    required this.status,
    required this.progressColor,
    required this.priorityIconColor,
  });

  
  static List<Task> tasks = [
    Task(
      title: 'Room 303 Set Up',
      category: 'Housekeeping',
      priority: 'High',
      mainIcon: Icons.cleaning_services,
      mainIconColor: Colors.blue,
      priorityIcon: Icons.signal_cellular_alt_rounded,
      priorityIconColor: Colors.red,
      progress: '30',
      page: 2,
      dueDate: '14 July 2024, 05:00 PM',
      assignedTo: 'Garima Bhatia',
      status: 'In-progress',
      progressColor: Colors.orange,
    ),
    Task(
      title: 'Fire Place Check & Up',
      category: 'Maintenance &...',
      priority: 'Low',
      mainIcon: Icons.miscellaneous_services_outlined,
      mainIconColor: Colors.deepPurpleAccent,
      priorityIcon: Icons.signal_cellular_alt_1_bar,
      priorityIconColor: Colors.green,
      progress: '0',
      page: 0,
      dueDate: '14 July 2024, 05:00 PM',
      assignedTo: 'Ranganathan',
      status: 'To do task',
      progressColor: const Color.fromARGB(255, 248, 224, 3),
    ),
    Task(
      title: 'Water Leakage Repair',
      category: 'Raise a Incident',
      priority: 'Low',
      mainIcon: Icons.water_damage_outlined,
      mainIconColor: Colors.red,
      priorityIcon: Icons.signal_cellular_alt_1_bar,
      priorityIconColor: Colors.green,
      progress: '100',
      page: 5,
      dueDate: '14 July 2024, 05:00 PM',
      assignedTo: 'Mahesh Taluk..',
      status: 'Completed',
      progressColor: Colors.green,
    ),
    Task(
      title: 'Door Lock Installat...',
      category: 'Custom',
      priority: 'Low',
      mainIcon: Icons.door_front_door,
      mainIconColor: Colors.orange,
      priorityIcon: Icons.signal_cellular_alt_1_bar,
      priorityIconColor: Colors.green,
      progress: 'Approval Awaited',
      page: 5,
      dueDate: '14 July 2024, 05:00 PM',
      assignedTo: 'Mahender Singh ',
      status: 'Overdue',
      progressColor: Colors.red,
    ),
    Task(
      title: 'WEEKLY FIRE DRILL SESS..',
      category: 'Custom',
      priority: 'Low',
      mainIcon: Icons.door_back_door,
      mainIconColor: Colors.orange,
      priorityIcon: Icons.signal_cellular_alt_1_bar,
      priorityIconColor: Colors.green,
      progress: 'Task Not Started',
      page: 0,
      dueDate: '14 July 2024, 05:00 PM',
      assignedTo: 'Ranjith Swami',
      status: 'Overdue',
      progressColor: Colors.red,
    ),
    Task(
      title: 'Room 303 Set Up',
      category: 'Housekeeping',
      priority: 'High',
      mainIcon: Icons.cleaning_services,
      mainIconColor: Colors.blue,
      priorityIcon: Icons.signal_cellular_alt_rounded,
      priorityIconColor: Colors.red,
      progress: '0',
      page: 0,
      dueDate: '14 July 2024, 05:00 PM',
      assignedTo: 'Garima Bhatia',
      status: 'To do task',
      progressColor: const Color.fromARGB(255, 248, 224, 3),
    ),
    Task(
      title: 'Water Leakage Repair',
      category: 'Raise a Incident',
      priority: 'Low',
      mainIcon: Icons.water_damage_outlined,
      mainIconColor: Colors.red,
      priorityIcon: Icons.signal_cellular_alt_1_bar,
      priorityIconColor: Colors.green,
      progress: '0',
      page: 0,
      dueDate: '14 July 2024, 05:00 PM',
      assignedTo: 'Mahesh Taluk..',
      status: 'To do task',
      progressColor: const Color.fromARGB(255, 248, 224, 3),
    ),
    Task(
      title: 'Door Lock Installat...',
      category: 'Custom',
      priority: 'Low',
      mainIcon: Icons.door_front_door,
      mainIconColor: Colors.orange,
      priorityIcon: Icons.signal_cellular_alt_1_bar,
      priorityIconColor: Colors.green,
      progress: '0',
      page: 0,
      dueDate: '14 July 2024, 05:00 PM',
      assignedTo: 'Mahender Singh ',
      status: 'To do task',
      progressColor: const Color.fromARGB(255, 248, 224, 3),
    ),
    Task(
      title: 'Room 303 Set Up',
      category: 'Housekeeping',
      priority: 'High',
      mainIcon: Icons.cleaning_services,
      mainIconColor: Colors.blue,
      priorityIcon: Icons.signal_cellular_alt_rounded,
      priorityIconColor: Colors.red,
      progress: 'Approval Awaited',
      page: 5,
      dueDate: '14 July 2024, 05:00 PM',
      assignedTo: 'Garima Bhatia',
      status: 'Overdue',
      progressColor: Colors.red,
    ),
    Task(
      title: 'Fire Place Check & Up',
      category: 'Maintenance &...',
      priority: 'Low',
      mainIcon: Icons.miscellaneous_services_outlined,
      mainIconColor: Colors.deepPurpleAccent,
      priorityIcon: Icons.signal_cellular_alt_1_bar,
      priorityIconColor: Colors.green,
      progress: 'Task Not Started',
      page: 0,
      dueDate: '14 July 2024, 05:00 PM',
      assignedTo: 'Ranganathan',
      status: 'Overdue',
      progressColor: Colors.red,
    ),
    Task(
      title: 'Water Leakage Repair',
      category: 'Raise a Incident',
      priority: 'Low',
      mainIcon: Icons.water_damage_outlined,
      mainIconColor: Colors.red,
      priorityIcon: Icons.signal_cellular_alt_1_bar,
      priorityIconColor: Colors.green,
      progress: 'Approval Awaited',
      page: 5,
      dueDate: '14 July 2024, 05:00 PM',
      assignedTo: 'Mahesh Taluk..',
      status: 'Overdue',
      progressColor: Colors.red,
    ),
    Task(
      title: 'Fire Place Check & Up',
      category: 'Maintenance &...',
      priority: 'Low',
      mainIcon: Icons.miscellaneous_services_outlined,
      mainIconColor: Colors.deepPurpleAccent,
      priorityIcon: Icons.signal_cellular_alt_1_bar,
      priorityIconColor: Colors.green,
      progress: '60',
      page: 3,
      dueDate: '14 July 2024, 05:00 PM',
      assignedTo: 'Ranganathan',
      status: 'In-progress',
      progressColor: Colors.orange,
    ),
    Task(
      title: 'Water Leakage Repair',
      category: 'Raise a Incident',
      priority: 'Low',
      mainIcon: Icons.water_damage_outlined,
      mainIconColor: Colors.red,
      priorityIcon: Icons.signal_cellular_alt_1_bar,
      priorityIconColor: Colors.green,
      progress: '90',
      page: 4,
      dueDate: '14 July 2024, 05:00 PM',
      assignedTo: 'Mahesh Taluk..',
      status: 'In-progress',
      progressColor: Colors.orange,
    ),
    Task(
      title: 'Door Lock Installat...',
      category: 'Custom',
      priority: 'Low',
      mainIcon: Icons.door_front_door,
      mainIconColor: Colors.orange,
      priorityIcon: Icons.signal_cellular_alt_1_bar,
      priorityIconColor: Colors.green,
      progress: '10',
      page: 1,
      dueDate: '14 July 2024, 05:00 PM',
      assignedTo: 'Mahender Singh ',
      status: 'In-progress',
      progressColor: Colors.orange,
    ),
    Task(
      title: 'Room 303 Set Up',
      category: 'Housekeeping',
      priority: 'High',
      mainIcon: Icons.cleaning_services,
      mainIconColor: Colors.blue,
      priorityIcon: Icons.signal_cellular_alt_rounded,
      priorityIconColor: Colors.red,
      progress: '100',
      page: 5,
      dueDate: '14 July 2024, 05:00 PM',
      assignedTo: 'Garima Bhatia',
      status: 'Completed',
      progressColor: Colors.green,
    ),
    Task(
      title: 'Fire Place Check & Up',
      category: 'Maintenance &...',
      priority: 'Low',
      mainIcon: Icons.miscellaneous_services_outlined,
      mainIconColor: Colors.deepPurpleAccent,
      priorityIcon: Icons.signal_cellular_alt_1_bar,
      priorityIconColor: Colors.green,
      progress: '100',
      page: 5,
      dueDate: '14 July 2024, 05:00 PM',
      assignedTo: 'Ranganathan',
      status: 'Completed',
      progressColor: Colors.green,
    ),
    Task(
      title: 'Water Leakage Repair',
      category: 'Raise a Incident',
      priority: 'Low',
      mainIcon: Icons.water_damage_outlined,
      mainIconColor: Colors.red,
      priorityIcon: Icons.signal_cellular_alt_1_bar,
      priorityIconColor: Colors.green,
      progress: '100',
      page: 5,
      dueDate: '14 July 2024, 05:00 PM',
      assignedTo: 'Mahesh Taluk..',
      status: 'Completed',
      progressColor: Colors.green,
    ),
  ];
}
